import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LoadingOverlay from "@/components/LoadingOverlay";
import { Toaster } from 'react-hot-toast'
import Loader from "@/components/Laoder";
import { LoadingProvider } from "@/components/LoadingProvider";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <Loader/> */}
        <LoadingProvider>

          <LoadingOverlay />
          {children}
          <Toaster position="top-right" />
        </LoadingProvider>
      </body>
    </html>
  );
}
